# fly.toml app configuration file for Telegram bot
app = "video-bot"
primary_region = "fra"

[build]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app/src"

[processes]
app = "python run_bot.py"
